# This is a basic workflow to help you get started with Actions

name: workflow-cicd-manual-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      inputstr:
        description: 'Greeting to send'
        required: true
        default: 'Hello'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  skip-or-run:
    if: ${{ inputs.inputstr == 'hoge'}}  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: new name skip # this is job name

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Display greeting
        run: echo "${{ inputs.greeting }}!"

  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.9.3'
          enable-cache: true
      - name: Install the project dependencies
        run: |
          uv sync --locked --all-extras --dev
      - name: Lint and format with Ruff
        run: |
          uv run ruff check . 
      - name: Run tests
        run: |
          uv run pytest ./tests
